### PR TITLE
PostGreSQL support

### PR DESCRIPTION
**Pull request by biscuitWizard**
Adds postgres to toaststunt.

sql_query(STR query[, LIST parameters]) => LIST of rows of LIST columns

sql_query is background_threaded and can be blocking if threads are set to 0.

### CODE REVIEW

**Comment by lisdude** [comment]
This doesn't seem to compile in Ubuntu or Gentoo: `postgres.cc:126:14: error: ‘params’ in namespace ‘pqxx’ does not name a type`

**Comment by biscuitWizard** [comment]
Interesting, can you help me debug? I've never used gentoo. I compiled on arch linux.

**Comment by biscuitWizard** [comment]
The version I'm using is libpqxx-7.6.0, there was a recent update to libpqxx, maybe the version hasn't replicated yet?

**Comment by lisdude** [comment]
What version of libpqxx are you using? Ubuntu is way out of date with 6.4 and Gentoo is at 7.2.1. I suspect something in the API changed and Arch has the latest version.

**Comment by biscuitWizard** [comment]
I suspect you're right. https://packages.gentoo.org/packages/dev-libs/libpqxx

**Comment by biscuitWizard** [comment]
2021-07-28: libpqxx 7.6.0 released
Deprecated dynamic_params in favour of params.

**Pull request closed without merging**
