### PR TITLE
Add all_properties and tomap functions

### PR DESCRIPTION
**Pull request by NathanTech7713**
This PR adds:
all_properties >= returns a list of all the properties on n including ancestors.

tomap >= returns a datatype as a map, for waifs and objects, it freezes them  with keys as prop names and values as prop values.

I'd love someone with more experience than me to have a squint at the code in case I missed any memory problems.

### CODE REVIEW

**Comment by biscuitWizard** [comment]
Hi Nathan,

My recommendation for all_properties is to instead do this in MOOcode rather than hardcode. Hardcode should be really reserved for things that cannot be done in Moocode, given there's a hard limit on how many built ins can exist.
`
{target} = args;
props = {};
for o in ({target, @ancestors(target)})
  for p in (properties(o))
    props = setadd(props, p);
  endfor
endfor
return props;
`
For example does what you want it to do.

tomap is interesting, but can be again done via moocode.

**Comment by NathanTech7713** [comment]
Hiya Biscuit,

Fair point on the all_properties thing, moo could do this with ease I agree. Honestly the only reason I put it in was because I used it in tomap and thought well... Might as well include it, it's useful :)

Relating to tomap though the reason I wanted to server side that one is speed. I know MOO has the print and to_value verbs for $string_utils which could probably be used in a manner to do tomap but I figured C would be a lot quicker. Granted, I could make it a lot quicker in MOO though!

Relating to this though, definitely don't approve this PR< I spotted several bugs (my bad) I'm still an apprentice level coder server side :)

**Comment by biscuitWizard** [comment]
I will say C is not measurably faster than MOOCode in a way that matters. You'd actually want to (for tomap) create the map then just toliteral() it, that has no string manipulation in it at all. :)

**Comment by distantorigin** [comment]
`Tomap` may be better handled by something like Shapes, an in-database object serialization library ($shapes in ToastCore, Improvise, and ChatMUD). $shapes is able to pull all properties and other values from a large object in < 0.01 seconds.

**Comment by distantorigin** [comment]
Closed by request.

**Pull request closed without merging**
